return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "go",
      "gomod",
      "gowork",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "svelte",
      "tsx",
      "typescript",
      "vim",
      "yaml",
    },
  },
}
